### ISSUE TITLE
Is this still working?

### ISSUE THREAD

**Issue by leonfilser** [schmid-sebastian/PaybackCoupons#1]
I really want to use this Tool but i wonder if it is still working?

**Comment by schmid-sebastian** [comment]
Hi Leon,

I just checked whether or not the activator is still working or not. Unfortunately, payback added the following bot check, which prevents the script from working:

![image](https://user-images.githubusercontent.com/51134424/108336420-4e900980-71d4-11eb-8ab2-e212aaaa4790.png)

**Comment by leonfilser** [comment]
That's a pity. Thanks for Checking!
